name: SoulJars
version: ${project.version}
author: TheBusyBiscuit
website: https://github.com/TheBusyBiscuit/souljars

api-version: "1.21"
main: com.github.drakescraft_labs.souljars.SoulJars

depend:
- Slimefun
